ignore:
  urls:
    - https://www.moddb.com/*
    - https://www.khronos.org/*
    - https://rutracker.org/forum/viewtopic.php?t=4008371
    - https://forums.getpaint.net/topic/4175-grid-maker-plugin/
    - https://ap-pro.ru/applications/core/interface/file/attachment.php?id=22581
    - https://modsfire.com/download/Fzg5Q2L2pcEHA8m/e9f70
    - https://wiki.synfig.org/TCB
    - https://wiki.nexusmods.com/index.php/How_to_create_mod_installers
    - https://disk.yandex.ru/d/7137tI653PRnrU
    - https://web.archive.org/web/20200918231136/http://stalkerin.gameru.net/wiki/index.php?title=%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D1%82_%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2_*.dm
