import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gettingstartedSidebar: [{type: 'autogenerated', dirName: 'getting-started'}],
  glossarySidebar: [{type: 'autogenerated', dirName: 'glossary'}],
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
  referencesSidebar: [{type: 'autogenerated', dirName: 'references'}],
  moddingtoolsSidebar: [{type: 'autogenerated', dirName: 'modding-tools'}],
  resourcesSidebar: [{type: 'autogenerated', dirName: 'resources'}],
  engineapiSidebar: [{type: 'autogenerated', dirName: 'engineapi'}],
  scriptingapiSidebar: [{type: 'autogenerated', dirName: 'scriptingapi'}],
  forcontributorsSidebar: [{type: 'autogenerated', dirName: 'forcontributors'}],
};

export default sidebars;
