import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
  referencesSidebar: [{type: 'autogenerated', dirName: 'references'}],
  moddingtoolsSidebar: [{type: 'autogenerated', dirName: 'modding-tools'}],
  resourcesSidebar: [{type: 'autogenerated', dirName: 'resources'}],
  forcontributorsSidebar: [{type: 'autogenerated', dirName: 'forcontributors'}],
};

export default sidebars;
