
name: Book Incorrect Translation
description: Incorrect Translation
labels: [Book Incorrect Translation]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Provide Incorrect Translation
    validations:
      required: true

