
name: Report Violation
description: Report Violation
labels: [Violation]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Provide Violation
    validations:
      required: true

