name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository clone
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup mdBook and plugins
        run: |
          cargo install mdbook
          cargo install mdbook-admonish
          cargo install mdbook-mermaid
          cargo install mdbook-linkcheck

      - name: mdBook Build
        run: mdbook build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./book

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deploy on GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4